# https://www.appveyor.com/docs/appveyor-yml

install:
  - choco install zip
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/lcamichigan/make-idml/master/make-idml.cmd'

build_script:
  - cd "Envelope IDML"
  - ..\make-idml ..\Envelope.idml

test: off

artifacts:
  - path: Envelope.idml

skip_tags: true
